server:
  port: 9000

spring:
  application:
    name: course-online-gateway

  cloud:
    nacos:
      discovery:
        # nacos地址
        server-addr: 127.0.0.1:8848
    # 开启gateway服务发现路由
    gateway:
      discovery:
        locator:
          enabled: true
      # 路由匹配规则
      routes:
        # 设置路由id
        - id: course-online-core
          # 设置路由uri lb://nacos中注册的服务名
          uri: lb://${spring.cloud.gateway.routes[0].id}
          # 断言 路由规则
          predicates:
            - Path=/api/service/**
          # 路由重写
          filters:
            - RewritePath=/api/service(?<segment>/?.*),$\{segment}
        # 设置路由id
        - id: course-online-file
          # 设置路由uri lb://nacos中注册的服务名
          uri: lb://${spring.cloud.gateway.routes[1].id}
          # 断言 路由规则
          predicates:
            - Path=/api/file/**
          # 路由重写
          filters:
            - RewritePath=/api/file(?<segment>/?.*),$\{segment}

logging:
  level:
    com.halayang: debug
  file:
    path: ./logs/${spring.application.name}/${spring.application.name}.log
