server:
  port: 8000
  compression:
    enabled: true
    mime-types: application/json,application/xml,text/html,text/xml,text/plain

spring:
  application:
    name: course-online-core
  datasource:
    address: jdbc:mysql://localhost:3306/course-online
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: ${spring.datasource.address}?useSSL=true&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&transformedBitIsBoolean=true&autoReconnect=true&failOverReadOnly=false&allowMultiQueries=true&serverTimezone=GMT%2B8
    username: root
    password: 1234
    hikari:
      connection-timeout: 30000
      minimum-idle: 5
      maximum-pool-size: 30
      idle-timeout: 30000
      max-lifetime: 120000
      auto-commit: true
      connection-test-query: SELECT 1

security:
  address: 127.0.0.1:8250
  oauth2:
    client:
      client-id: core
      client-secret: 123456
      resource-ids: course-online
      user-authorization-uri: http://${security.address}/oauth/authorize
      access-token-uri: http://${security.address}/oauth/token
    resource:
      # 认证中心id
      id: server
      token-info-uri: http://${security.address}/oauth/check_token
      user-info-uri: http://${security.address}/oauth/principal


# Feign 配置
feign:
  compression:
    request:
      # 开启请求压缩
      enabled: true
      # 配置压缩的 MIME TYPE
      mime-types: text/xml,application/xml,application/json
      # 配置压缩数据大小的下限
      min-request-size: 1024
    response:
      # 开启响应压缩
      enabled: true
      useGzipDecoder: true

mybatis-plus:
  configuration:
    # 开启缓存
    cache-enabled: true
    # 开启懒加载
    lazy-loading-enabled: true
    # 开启驼峰命名规则映射
    map-underscore-to-camel-case: true
    # 不映射空值的列
    call-setters-on-nulls: false
  global-config:
    db-config:
      # 逻辑删除插件
      logic-delete-field: is_delete
      logic-delete-value: 1
      logic-not-delete-value: 0
  mapper-locations: classpath:/mapper/**/*.xml
  # 别名设置pojo类所处的包路径
  type-aliases-package: com.halayang.server.*.po
# pagehelper配置
pagehelper:
  helper-dialect: mysql
  pageSizeZero: true
  params: count=countSql
  reasonable: true
  support-methods-arguments: true

logging:
  level:
    com.halayang: debug
  file:
    path: ./logs/${spring.application.name}/${spring.application.name}.log
